package br.com.warrick.biblioteca.view.screens.livro;

import java.awt.Color;

/**
 * Projeto: Biblioteca
 *
 * @author Warrick
 * @since 02/11/2025
 */
public class Capa extends javax.swing.JPanel {

    /* ================================================= CONSTRUTOR ================================================= */
    public Capa(String titulo) {
        initComponents();

    }

    /* ============================================= USADO PARA ADAPTAR ============================================= */
    /**
     * Classe usada como base para mostar as capas do livro quando retirada da estante
     */
    /* ================================================== GETTERS =================================================== */
    public javax.swing.JLabel getlblTitulo() {
        return lblTitulo;
    }

    public javax.swing.JLabel getlblSigla() {
        return lblSigla;
    }

    public javax.swing.JLabel getlblSubTitulo() {
        return lblSubTitulo;
    }

    public javax.swing.JLabel getlblAutor() {
        return lblAutor;
    }

    /* ================================================== SETTERS =================================================== */
    public void setlblTitulo(javax.swing.JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    public void setlblSigla(javax.swing.JLabel lblSigla) {
        this.lblSigla = lblSigla;
    }

    public void setlblSubTitulo(javax.swing.JLabel lblSubTitulo) {
        this.lblSubTitulo = lblSubTitulo;
    }

    public void setlblAutor(javax.swing.JLabel lblAutor) {
        this.lblAutor = lblAutor;
    }

    public void setCorCapa(Color color) {
        setBackground(color);
        repaint();
    }

    /* ========================================== SETTERS DE COMPLETEMENTOS ========================================= */
    public void setCategoria(String categoria) {

    }

    public void setSubCategoria(String subCategoria) {

    }

    /**
     * Projeto: Biblioteca This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblSigla = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("TITULO");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 160, 550, 180));

        lblSigla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSigla.setText("KJA");
        add(lblSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 175, 31));

        lblSubTitulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblSubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitulo.setText("SUB TITULO");
        add(lblSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 560, 65));

        lblAutor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAutor.setText("FERNANDO SANTOS");
        add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 700, 550, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Capas1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblSigla;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
