package br.com.warrick.biblioteca.view.screens.livro;

/**
 * Classe usada para visualizar as paginas do livro
 * 
 * Projeto: Biblioteca
 *
 * @author Warrick
 * @since 02/11/2025
 */
public class Livro extends javax.swing.JPanel {

    /* ================================================= CONSTRUTOR ================================================= */
    public Livro() {
        initComponents();

    }

    /**
     * Projeto: Biblioteca This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
