package br.com.warrick.biblioteca.Livro;

import javax.swing.*;
import java.awt.*;

/**
 * Projeto: Biblioteca
 * @author Warrick
 * @since 02/11/2025
 */
public class Livro extends javax.swing.JPanel {

    private final String titulo;
    private final Color corLombada;
    private final JPanel lombada;
    private final JPanel capa;

    public Livro(String titulo, Color corLombada) {
        initComponents();
        this.titulo = titulo;
        this.corLombada = corLombada;
        setLayout(null);
        setSize(20, 100);

        // Lombada (visível na estante)
        lombada = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                g2d.setColor(Color.WHITE);
                g2d.rotate(Math.PI / 2);
                g2d.drawString(titulo, 5, -5);
            }
        };
        lombada.setBackground(corLombada);
        lombada.setBounds(0, 0, 20, 100);
        add(lombada);

        // Capa (escondida no começo)
        capa = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(new Color(255, 220, 150));
                g.fillRoundRect(10, 20, 130, 160, 15, 15);
                g.setColor(Color.BLACK);
                g.setFont(new Font("Serif", Font.BOLD, 14));
                g.drawString(titulo, 25, 100);
            }
        };
        capa.setBackground(new Color(200, 50, 50));
        capa.setBounds(0, 0, 170, 220);
        capa.setVisible(false);
        add(capa);
    }

    public void mostrarCapa() {
        lombada.setVisible(false);
        capa.setVisible(true);
    }

    public void mostrarLombada() {
        lombada.setVisible(true);
        capa.setVisible(false);
    }

    public String getTitulo() {
        return titulo;
    }

    /**
 * Projeto: Biblioteca
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
