package br.com.warrick.biblioteca.view.components.card;


/**
 * Componente de interface gráfica que representa um card de livro bíblico
 * Exibe informações como sigla, nome do livro e cânon, com suporte a interações do usuário
 *
 * Projeto: Biblioteca
 *
 * @author Warrick
 * @since 02/11/2025
 */
public class CardLivroBiblico extends javax.swing.JPanel {

    /* ================================================= CONSTRUTOR ================================================= */
    /**
     * Constrói um novo CardLivroBiblico e configura seus listeners
     */
    public CardLivroBiblico() {
        initComponents();
        setupListeners();
    }
    
    /* ================================================ MÉTODOS PRIVADOS ============================================ */
    /**
     * Configura os listeners de mouse para o componente
     * Inclui eventos para clique, entrada e saída do mouse
     */
    private void setupListeners() {
        lblPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Ação para clique: pode ser personalizado (ex.: abrir detalhes do livro)
                System.out.println("Card de livro bíblico clicado!");
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Ação para hover: mudar cor para indicar interação
                setCorFundo(java.awt.Color.LIGHT_GRAY);
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Ação para sair do hover: voltar cor original
                setCorFundo(java.awt.Color.WHITE);
            }
        });
    }

    /* ============================================== MÉTODOS PÚBLICOS ========================================= */
    
    /* ============================================== GETTERS E SETTERS ========================================= */
    public javax.swing.JLabel getlblSigla() {
        return lblSigla;
    }

    public javax.swing.JLabel getNomeCanone() {
        return lblNomeCanone;
    }

    public javax.swing.JLabel getNomeLivro() {
        return lblNomeLivro;
    }

    /* =================================================== SETTERS ================================================== */
    public void setlblSigla(javax.swing.JLabel lblSigla) {
        this.lblSigla = lblSigla;
    }

    public void setNomeCanone(javax.swing.JLabel lblNomeCanone) {
        this.lblNomeCanone = lblNomeCanone;
    }

    public void setNomeLivro(javax.swing.JLabel lblNomeLivro) {
        this.lblNomeLivro = lblNomeLivro;
    }   

    /**
     * Define a cor de fundo do card
     *
     * @param cor
     */
    public void setCorFundo(java.awt.Color cor) {
        if (cor != null) {
            this.setBackground(cor);
        }
    }

    /* ========================================= CÓDIGO GERADO PELO NETBEANS ========================================= */
    /**
     * Este método é chamado dentro do construtor para inicializar o formulário.
     * AVISO: NÃO modifique este código. O conteúdo deste método é sempre regenerado pelo Editor de Formulários.
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSigla = new javax.swing.JLabel();
        lblNomeCanone = new javax.swing.JLabel();
        lblNomeLivro = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(100, 65));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(100, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSigla.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblSigla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSigla.setText("Gn");
        add(lblSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        lblNomeCanone.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lblNomeCanone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeCanone.setText("Bereshit");
        add(lblNomeCanone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 100, 15));

        lblNomeLivro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeLivro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeLivro.setText("Gênesis");
        add(lblNomeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 100, 20));
        add(lblPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));
    }// </editor-fold>//GEN-END:initComponents


    /* ========================================= VARIÁVEIS DO NETBEANS ========================================= */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNomeCanone;
    private javax.swing.JLabel lblNomeLivro;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblSigla;
    // End of variables declaration//GEN-END:variables
}
