package br.com.warrick.biblioteca.card;

/**
 * Projeto: Biblioteca
 * @author Warrick
 * @since 02/11/2025
 */
public class CardNumero extends javax.swing.JPanel {

    public CardNumero() {
        initComponents();
        setupListeners();
    }
    
    /* =================================================== MÉTODOS ================================================== */
    // Método para configurar os listeners de mouse no label Pelicula
    private void setupListeners() {
        lblPeliculaNum.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Ação para clique: pode ser personalizado (ex.: selecionar o número)
                System.out.println("Card de número clicado!");
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Ação para hover: mudar cor para indicar interação
                setCorFundo(java.awt.Color.LIGHT_GRAY);
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Ação para sair do hover: voltar cor original
                setCorFundo(java.awt.Color.WHITE);
            }
        });
    }

    /** 
     * Getters e Setters para os componentes JLabel
     *
     * @return
     */
    /* =================================================== GETTERS ================================================== */
    public javax.swing.JLabel getlblNumero() {
        return lblNumero;
    }

    /* =================================================== SETTERS ================================================== */
    public void setlblNumero(javax.swing.JLabel lblNumero) {
        this.lblNumero = lblNumero;

    }

    /**
     * Métodos convenientes para definir numeros diretamente
     *
     * @param text
     */
    public void setNumero(String text) {
        if (lblNumero != null && text != null) {
            lblNumero.setText(text);
        }
    }

    /**
     * Define a cor de fundo do card
     *
     * @param cor Cor de fundo a ser aplicada
     */
    public void setCorFundo(java.awt.Color cor) {
        if (lblNumero != null) {
            lblNumero.setBackground(cor);
            lblNumero.setOpaque(true);            
        }
        this.setBackground(cor);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero = new javax.swing.JLabel();
        lblPeliculaNum = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(30, 30));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(30, 30));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("1");
        add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));
        add(lblPeliculaNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPeliculaNum;
    // End of variables declaration//GEN-END:variables
}
