package br.com.warrick.biblioteca.card;

/**
 * Projeto: Biblioteca
 * @author Warrick
 * @since 02/11/2025
 */
public class CardAbreviacao extends javax.swing.JPanel {

    public CardAbreviacao() {
        initComponents();
        setupListeners();
    }
    
    /* =================================================== MÉTODOS ================================================== */
    // Método para configurar os listeners de mouse no label Pelicula
    private void setupListeners() {
        lblPeliculaAbr.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Ação para clique: pode ser personalizado (ex.: selecionar o card)
                System.out.println("Card de abreviação clicado!");
            }
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Ação para hover: mudar cor para indicar interação
                setCorFundo(java.awt.Color.LIGHT_GRAY);
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Ação para sair do hover: voltar cor original
                setCorFundo(java.awt.Color.WHITE);
            }
        });
    }

    /* =================================================== GETTERS ================================================== */
    public javax.swing.JLabel getlblAbreviacao() {
        return lblAbreviacao;
    }

    public javax.swing.JLabel getlblPeliculaAbr() {
        return lblPeliculaAbr;
    }

    /* =================================================== SETTERS ================================================== */
    public void setlblAbreviacao(javax.swing.JLabel lblAbreviacao) {
        this.lblAbreviacao = lblAbreviacao;
    }

    /**
     *
     * Métodos convenientes para definir conteudo diretamente
     */
    public void setAbreviacao(String text) {
        if (lblAbreviacao != null && text != null) {
            lblAbreviacao.setText(text);
        }
    }    

    /**
     * Define a cor de fundo do card
     *
     * @param cor
     */
    public void setCorFundo(java.awt.Color cor) {
        if (lblAbreviacao != null) {
            lblAbreviacao.setBackground(cor);
            lblAbreviacao.setOpaque(true);
        }
        this.setBackground(cor);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAbreviacao = new javax.swing.JLabel();
        lblPeliculaAbr = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAbreviacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbreviacao.setText("ARA");
        add(lblAbreviacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 45, 45));
        add(lblPeliculaAbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 45, 45));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAbreviacao;
    private javax.swing.JLabel lblPeliculaAbr;
    // End of variables declaration//GEN-END:variables
}
