package br.com.warrick.biblioteca.view.login;

/**
 * Projeto: Biblioteca
 * @author Warrick
 * @since 02/11/2025
 */
public class LoginFrente extends javax.swing.JPanel {

    /** Referência para a aplicação pai, usada para navegação entre telas. */
    private LoginApp parentApp;

    /** Construtor padrão. Inicializa os componentes da interface e configura os listeners. */
    public LoginFrente() {
        initComponents();
        setOpaque(false);
        setBackground(new java.awt.Color(0, 0, 0, 0));
        setupListeners();
    }

    /** Construtor que aceita uma referência para a aplicação pai. Permite integração com a aplicação principal para transições de tela. */
    public LoginFrente(LoginApp parentApp) {
        this.parentApp = parentApp;
        initComponents();
        setOpaque(false);
        setBackground(new java.awt.Color(0, 0, 0, 0));
        setupListeners();
    }

    /** Método privado para configurar os event listeners dos componentes da interface. Adiciona ações para botões de login, sair e link de registro. */
    private void setupListeners() {
        // Configurar listeners após initComponents para evitar interferência no código gerado automaticamente
        // Configurar ação do botão de login: validar credenciais e iniciar aplicação
        cmdLogin.addActionListener(e -> {
            // Obter o nome de usuário inserido, removendo espaços em branco
            String usuario = txtUsuario.getText().trim();
            // Obter a senha inserida como string
            String senha = new String(txtSenha.getPassword());

            // Usar controller para login
            br.com.warrick.biblioteca.controller.UsuarioController controller
                    = new br.com.warrick.biblioteca.controller.UsuarioController();

            if (controller.fazerLogin(usuario, senha)) {
                lblInfo3.setText("Login bem-sucedido!");
                lblInfo3.setForeground(java.awt.Color.GREEN);

                // Fechar a janela de login
                java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
                if (window != null) {
                    window.dispose();
                }

                // Iniciar a aplicação principal em uma nova thread
                new Thread(() -> {
                    try {
                        System.out.println("Iniciando LApp...");
                        br.com.warrick.biblioteca.view.login.LoginLoadingPainel.executar();
                        System.out.println("LApp iniciado com sucesso!");
                    } catch (Exception ex) {
                        System.err.println("Erro ao iniciar LApp: " + ex.getMessage());
                        ex.printStackTrace();
                    }
                }).start();
            } else {
                lblInfo3.setText("Usuário ou senha inválidos.");
                lblInfo3.setForeground(java.awt.Color.RED);
            }
        });

        // Configurar ação do botão sair: encerrar a aplicação
        cmdSair.addActionListener(e -> System.exit(0));

        // Configurar listener para o label de registro: navegar para tela de registro
        lblInfo4.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (parentApp != null) {
                    parentApp.mostrarRegistro();
                }
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInfo4.setForeground(java.awt.Color.CYAN);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInfo4.setForeground(java.awt.Color.WHITE);
            }
        });
    }

    /**
     * Projeto: Biblioteca This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();
        txtUsuario = new br.com.warrick.biblioteca.peripherals.TextFieldLogin();
        txtSenha = new br.com.warrick.biblioteca.peripherals.PasswordFieldLogin();
        lblInfo1 = new javax.swing.JLabel();
        lblInfo2 = new javax.swing.JLabel();
        lblInfo3 = new javax.swing.JLabel();
        cmdLogin = new br.com.warrick.biblioteca.peripherals.WButton();
        cmdSair = new br.com.warrick.biblioteca.peripherals.WButton();
        lblInfo4 = new javax.swing.JLabel();
        lblTitulo4 = new javax.swing.JLabel();
        lblTitulo5 = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(204, 153, 0));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("LOGIN");
        add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 70, 407, 60));

        lblTitulo2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(204, 153, 0));
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo2.setText("Um bom livro não se abre sozinho…");
        lblTitulo2.setToolTipText("");
        add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 135, 407, 20));

        lblTitulo3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(221, 171, 20));
        lblTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo3.setText("Mas com um clique, ele ganha vida.");
        lblTitulo3.setToolTipText("");
        add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 160, 407, 30));

        txtUsuario.setForeground(new java.awt.Color(255, 204, 0));
        txtUsuario.setCaretColor(new java.awt.Color(255, 204, 51));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setLabelText("USUÁRIO");
        txtUsuario.setMinimumSize(new java.awt.Dimension(64, 46));
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 360, 50));

        txtSenha.setForeground(new java.awt.Color(255, 204, 0));
        txtSenha.setCaretColor(new java.awt.Color(255, 255, 0));
        txtSenha.setDisabledTextColor(new java.awt.Color(255, 204, 0));
        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSenha.setLabelText("SENHA");
        add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 360, 50));

        lblInfo1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblInfo1.setForeground(new java.awt.Color(153, 0, 0));
        lblInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo1.setToolTipText("");
        add(lblInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 375, 200, 25));

        lblInfo2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblInfo2.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInfo2.setText("Esqueci minha senha...");
        lblInfo2.setToolTipText("");
        add(lblInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 375, 200, 25));

        lblInfo3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblInfo3.setForeground(new java.awt.Color(153, 0, 0));
        lblInfo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo3.setToolTipText("");
        add(lblInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 415, 407, 30));

        cmdLogin.setForeground(new java.awt.Color(204, 153, 0));
        cmdLogin.setText("LOGIN");
        cmdLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        add(cmdLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 170, 50));

        cmdSair.setForeground(new java.awt.Color(153, 51, 0));
        cmdSair.setText("SAIR");
        cmdSair.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        add(cmdSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 170, 50));

        lblInfo4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblInfo4.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo4.setText("Não tem conta? Registre-se!");
        lblInfo4.setToolTipText("");
        add(lblInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 510, 250, 30));

        lblTitulo4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTitulo4.setForeground(new java.awt.Color(255, 204, 0));
        lblTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo4.setText("Uma biblioteca não é só de livros…");
        lblTitulo4.setToolTipText("");
        add(lblTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 550, 407, 40));

        lblTitulo5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTitulo5.setForeground(new java.awt.Color(255, 204, 0));
        lblTitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo5.setText("é de histórias que se conectam.");
        lblTitulo5.setToolTipText("");
        add(lblTitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 580, 407, 40));

        lblFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/LivroLogin.png"))); // NOI18N
        add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.warrick.biblioteca.peripherals.WButton cmdLogin;
    private br.com.warrick.biblioteca.peripherals.WButton cmdSair;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblInfo3;
    private javax.swing.JLabel lblInfo4;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    private br.com.warrick.biblioteca.peripherals.PasswordFieldLogin txtSenha;
    private br.com.warrick.biblioteca.peripherals.TextFieldLogin txtUsuario;
    // End of variables declaration//GEN-END:variables
}
