package br.com.warrick.biblioteca.view.login;

import java.awt.Color;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 * Projeto: Biblioteca
 * @author Warrick
 * @since 02/11/2025
 */
public class LoginApp extends javax.swing.JFrame {

    // Layout para alternar entre os painéis de login e registro
    private CardLayout cardLayout;
    // Painel principal que contém os subpainéis
    private JPanel mainPanel;
    // Painel frontal de login
    private LoginFrente loginFrente;
    // Painel traseiro de registro
    private LoginTras loginTras;

    // Construtor da aplicação de login
    public LoginApp() {
        setUndecorated(true);
        initComponents();
        setupTransparentWindow();
        setupPanels();
    }

    private void setupTransparentWindow() {
        // Configurar para que apenas o fundo seja transparente
        setBackground(new Color(0, 0, 0, 0));
        getRootPane().setOpaque(false);
        getContentPane().setBackground(new Color(0, 0, 0, 0));
    }

    private void setupPanels() {
        // Criar CardLayout para alternar entre painéis
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);
        mainPanel.setOpaque(false);
        mainPanel.setBackground(new Color(0, 0, 0, 0));

        // Criar instâncias dos painéis
        loginFrente = new LoginFrente(this);
        loginTras = new LoginTras(this);

        // Adicionar painéis ao CardLayout
        mainPanel.add(loginFrente, "LOGIN");
        mainPanel.add(loginTras, "REGISTRO");

        // Adicionar o painel principal à janela
        add(mainPanel);

        // Mostrar painel de login inicialmente
        cardLayout.show(mainPanel, "LOGIN");
    }

    // Métodos para alternar entre painéis
    public void mostrarLogin() {
        cardLayout.show(mainPanel, "LOGIN");
    }

    public void mostrarRegistro() {
        cardLayout.show(mainPanel, "REGISTRO");
    }

    /**
 * Projeto: Biblioteca
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(528, 704));
        setSize(new java.awt.Dimension(528, 704));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
